- name: Add a new AP
  aci_ap:
    host: "{{aci_host}}"
    username: "{{aci_username}}"
    password: "{{aci_password}}"
    port: "{{aci_port}}"
    validate_certs: "{{aci_validate_certs}}"
    tenant: "{{aci_tenant}}"
    ap: "{{item}}"
    description: default ap
    state: "{{aci_state}}"
  delegate_to: localhost
  loop: "{{ap_applications}}"
